// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: cartDetail.sql

package db

import (
	"context"
)

const createCartDetail = `-- name: CreateCartDetail :one
INSERT INTO "cartDetails" (
  cart_id,
  product_id,
  quantity_added
) VALUES (
    $1, $2, $2
)
RETURNING id, cart_id, product_id, quantity_added
`

type CreateCartDetailParams struct {
	CartID    int64 `json:"cart_id"`
	ProductID int64 `json:"product_id"`
}

func (q *Queries) CreateCartDetail(ctx context.Context, arg CreateCartDetailParams) (CartDetail, error) {
	row := q.db.QueryRow(ctx, createCartDetail, arg.CartID, arg.ProductID)
	var i CartDetail
	err := row.Scan(
		&i.ID,
		&i.CartID,
		&i.ProductID,
		&i.QuantityAdded,
	)
	return i, err
}
