// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: orderDetail.sql

package db

import (
	"context"
)

const createOrderDetail = `-- name: CreateOrderDetail :one
INSERT INTO "orderDetails" (
    product_id,
    username,
    quantity_ordered,
    price_at_time_of_order,
    order_id
) 
VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, product_id, username, quantity_ordered, price_at_time_of_order, order_id
`

type CreateOrderDetailParams struct {
	ProductID          int64   `json:"product_id"`
	Username           string  `json:"username"`
	QuantityOrdered    int64   `json:"quantity_ordered"`
	PriceAtTimeOfOrder float64 `json:"price_at_time_of_order"`
	OrderID            int64   `json:"order_id"`
}

func (q *Queries) CreateOrderDetail(ctx context.Context, arg CreateOrderDetailParams) (OrderDetail, error) {
	row := q.db.QueryRow(ctx, createOrderDetail,
		arg.ProductID,
		arg.Username,
		arg.QuantityOrdered,
		arg.PriceAtTimeOfOrder,
		arg.OrderID,
	)
	var i OrderDetail
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Username,
		&i.QuantityOrdered,
		&i.PriceAtTimeOfOrder,
		&i.OrderID,
	)
	return i, err
}
