// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: order.sql

package db

import (
	"context"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (
    username,
    total_price,
    status
) 
VALUES (
    $1, $2, $3
)
RETURNING id, username, total_price, status, created_at
`

type CreateOrderParams struct {
	Username   string  `json:"username"`
	TotalPrice float64 `json:"total_price"`
	Status     string  `json:"status"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder, arg.Username, arg.TotalPrice, arg.Status)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.TotalPrice,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
