// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	ClearCart(ctx context.Context, cartID int64) error
	CreateCart(ctx context.Context, username string) (Cart, error)
	CreateCartDetail(ctx context.Context, arg CreateCartDetailParams) (CartDetail, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreateOrderDetail(ctx context.Context, arg CreateOrderDetailParams) (OrderDetail, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteCart(ctx context.Context, username string) error
	DeleteCartDetail(ctx context.Context, arg DeleteCartDetailParams) error
	DeleteProduct(ctx context.Context, id int64) error
	GetCartByID(ctx context.Context, id int64) (Cart, error)
	GetCartByUsername(ctx context.Context, username string) (Cart, error)
	GetCartDetail(ctx context.Context, arg GetCartDetailParams) (CartDetail, error)
	GetCartDetailsByCartID(ctx context.Context, cartID int64) ([]CartDetail, error)
	GetProduct(ctx context.Context, id int64) (Product, error)
	GetSession(ctx context.Context, id uuid.UUID) (Session, error)
	GetUser(ctx context.Context, username string) (User, error)
	UpdateCartDetail(ctx context.Context, arg UpdateCartDetailParams) (CartDetail, error)
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
